### PR TITLE
Disable extensive memory sanity checks in CI

### PR DESCRIPTION
**Pull request by luc-blaeser**
Introducing a switch for extensive memory sanity checks as used in the generational GC. 

Disable these checks in CI, as they otherwise take too long with `ic-ref-run`.

To enable the checks during engineering or testing, manually set the features in `Cargo.toml` as follows:
```
[features]
default = ["ic", "memory_check"]
```

### CODE REVIEW

**Comment by crusso** [comment]
Did this reduce the CI times at all?

**Comment by luc-blaeser** [comment]
> Did this reduce the CI times at all?

I will compare and verify this with a second CI build without this option. It still took 2h55m: https://github.com/dfinity/motoko/actions/runs/3648374585/jobs/6161720339

**Comment by crusso** [comment]
I wonder if we should also just disable all sanity checks on ic-ref, in the moc compiler itself, perhaps.

**Review by crusso — APPROVED** [review]

**Comment by luc-blaeser** [comment]
Resolved with https://github.com/dfinity/motoko/pull/3652

**Pull request closed without merging**
