### PR TITLE
Units design proposal

### PR DESCRIPTION
**Pull request by rossberg**
Okay, this proposal attempts to define a simple and coherent model for source files, import semantics, and compilation, It is intended to address #400 and other related discussion; it's a sort of remix of the approaches already discussed in that thread. Please take a look.

### CODE REVIEW

**Review by nomeata — COMMENTED** [review]
Thanks for starting to write this up.

I am slightly disappointed that you don’t even acknowledge the work that the rest of the team poured into the [current `import` design](https://dfinity.atlassian.net/wiki/spaces/AST/pages/147357892/ActorScript+library+import), including some intense hours in Zurich, and that design was not callenged more timely. It also “ makes each of these use cases possible and convenient while unifying them as much as possible.”, maybe even more uniformly.

**Review by matthewhammer — APPROVED** [review]
LGTM.

My only outstanding comments are about the precise compiler flags we choose.  I like @nomeata's suggestion of distinguishing the three conceptual cases, since then the compiler can know the user's intention with the output, and issue more helpful messages.  I don't see the benefit to the alternative, where one or more flags are conflated.

**Review by nomeata — CHANGES_REQUESTED** [review]
(I guess I should make it explicit that there are open issues, lest it gets merged accidentally because of one approving review.)

**Review by crusso — CHANGES_REQUESTED** [review]
I think this still need some iteration.

FTR, I still don't see what is wrong with the existing import mechanism Joachim came up with, which is clean yet expressive. There is no reason to require an import to be a module - all we need it to be is pure and the same mechanism that is used to reconstruct a module value from a wasm module, which will need to be module-type directed, can be used to construct any old value from a wasm module and an arbitrary AS type. With Joachim's proposal, pattern matching on libraries comes for free too and doesn't need to be built into the syntax.

I also don't grok the objection to requiring `module { ... }` around library implementations (when they are, in fact, literal modules). An advantage of this that the implementation could also be just a projection or, if extend the notion of static appropriately, an application of a pure function (perhaps for pure functors).
Provided the syntax for fields and expressions doesn't overlap then we could even treat the fields* as shorthand for `module { fields* }` yet still support arbitrary (static) expressions as libraries).

On the other hand, I agree that the use case for importing non-module libraries is quite limited, but I don't think it's fundamentally flawed. 

I sympathise with @kRITZCREEK  that prefix `import` makes the IDE problem a little simpler, but a simple lex of the file for `IMPORT STRING` token sequences should be sufficient yet much quicker than a full parse.

**Review by matthewhammer — CHANGES_REQUESTED** [review]
Good stuff!  I have two minor suggestions.

**Comment by luc-blaeser** [comment]
Just doing some repo cleanup for better focussing on active work:
Closing PR as it seems inactive for a longer time. Please re-open if it is still relevant and after it has been updated with latest master changes.

**Pull request closed without merging**
