### PR TITLE
Add `bat` to the shell toolset

### PR DESCRIPTION
**Pull request by ggreif**
a small colored `cat` utility, highlighting code

### CODE REVIEW

**Review by nomeata — DISMISSED** [review]
Ok, (in general I don't think we should all useful random unrelated tools.)

**Comment by ggreif** [comment]
> Ok, (in general I don't think we should all useful random unrelated tools.)

Heh, it's like 2 tools per year, maybe with a decreasing cadence :-)

**Comment by ggreif** [comment]
@rvanasa currently `bat` won't highlight Motoko (and neither Viper), do you have an idea what it would take to add support for them?

**Comment by luc-blaeser** [comment]
Just doing some repo cleanup for better focussing on active work:
Closing PR as it seems inactive for a longer time. Please re-open if it is still relevant and after it has been updated with latest master changes.

**Pull request closed without merging**
