### PR TITLE
include DWARF in debug sections

### PR DESCRIPTION
**Pull request by ggreif**
Last chunk.

Contains the linker tweaks, `compile.ml` changes, and the tests.

----------
OLD stuff.

I am putting this up for review the only thing that comes to my mind that could be broken out is the `RUN:`-line handling for `FileCheck`. Not convinced it is worth it.

I have marked areas in need of cleanup, but they might be useful for a context of what is being generated. Feedback is welcome if more prose explanations (notes) are necessary.

Joachim submitted a few comments about the code wrapping changes in `compile.ml` (mostly naming conventions), this will be addressed next. (Done in #1576.)

I wonder why the gas-consumption went up, the generated code shouldn't change.

---------------

Start generating DWARF for Motoko source.

Part of #1244

Laundry list:
- [x] make tests pass
- [x] remove warnings (`nix-build`)
- [x] get back to stock `OCaml`
- [x] document how DIEs are formed (both sides)
- [x] cut out a bunch of smaller changes into other PRs
  - #1547 (merged)
  - #1576 (merged)
  - #1949 (merged)
  - #2071 (merged)
- [x] get peephole optimiser right even in the presence of `Meta` instructions
- [x] write the note about references (bubbling-up)
- [x] fix regressions
- [x] merge conflicts: rectify `compile.ml`
- [ ] make sure that no tags are created when `-g` not passed
- [x] remove `effects`
- [ ] introduce a switch to disable peephole optimisation (reveals whether activating `-g` changes code)

### CODE REVIEW

**Review by nomeata — COMMENTED** [review]
A first high-level pass. Mostly worried about the abuse of souce location, instead of using a proper data type.

**Comment by ggreif** [comment]
> Thanks again for taking this on!

This compiles, but I am pretty sure the generated DWARF is spotty. I have to go through more thunks and do the rework. Will try to do it gradually.

**Comment by rvanasa** [comment]
Gotcha; no rush at all, since this is relatively low-priority on my end for the next few weeks.

**Comment by luc-blaeser** [comment]
Just doing some repo cleanup for better focussing on active work:
Closing PR as it seems inactive for a longer time. Please re-open if it is still relevant and after it has been updated with latest master changes.

**Pull request closed without merging**
