### PR TITLE
just a test PR

### PR DESCRIPTION
**Pull request by ggreif**

### CODE REVIEW

**Review by ggreif — COMMENTED** [review]
@nomeata please rubber-stamp!

**Review by crusso — APPROVED** [review]

**Comment by ggreif** [comment]
@MergifyIO update

**Comment by ggreif** [comment]
@Mergifyio refresh

**Comment by ggreif** [comment]
@Mergifyio update

**Comment by ggreif** [comment]
@Mergifyio squash

**Comment by ggreif** [comment]
@Mergifyio can you *ing merge this PR, finally!

**Comment by ggreif** [comment]
@Mergifyio refresh

**Comment by ggreif** [comment]
## Because

> File Used
> Mergify uses the configuration file that is:
> 
> The file named `.mergify.yml`, or, as a fallback, `.mergify/config.yml` or `.github/mergify.yml` from the root directory.
> In the default repository branch configured on GitHub — usually `main`.

**Comment by ggreif** [comment]
this won't do what I want

**Pull request closed without merging**
