### PR TITLE
Fix code highlighting styles in doc preview

### PR DESCRIPTION
**Pull request by rvanasa**
See #3366

### CODE REVIEW

**Review by chenyan-dfinity — APPROVED** [review]
Can we propagate the change to portal repo, and enable dark mode there?

**Comment by rvanasa** [comment]
> Can we propagate the change to portal repo, and enable dark mode there?

Sure; I'll look into this.

**Comment by rvanasa** [comment]
Added a PR to propagate changes from this repo (dfinity/portal#328). Dark mode works almost perfectly for the Motoko documentation in the developer portal, but other pages (especially the homepage) have custom styles that cause problems when dark mode is enabled. These changes will at least make it much easier to implement a dark theme in the future.

**Comment by crusso** [comment]
Thanks @rvanasa. Note I squash merged the base PR so you may need to adjust this one somehow (or cherry pick newer commits to a separate branch).

**Pull request merged**
