### PR TITLE
Test for PR #1992

### PR DESCRIPTION
**Pull request by crusso**
Adds a test to check gc handles iterators properly, as a PR to osa1/fix_tuple_len_fields (not master!)

### CODE REVIEW

**Review by ggreif — CHANGES_REQUESTED** [review]
Checked that the third line in @osa1's patch is triggered by the tests, the first too. But the second (blob-like text) isn't. Let me add a test case too.

**Review by ggreif — COMMENTED** [review]
Actually the second fix is also exercised, but I had to help it with
``` C
    TUPLE_LEN(c) = 30;
```
so that it actually started crashing.

**Review by ggreif — APPROVED** [review]
As such, this can go in. I think it is OK to send both the fix and the tests (at the same time or one after another) now that all three lines of the fix are checked. I'll leave this to both of you.

**Review by osa1 — APPROVED** [review]
Great, thanks @crusso !

**Pull request merged**
