### PR TITLE
Remove own `default_uncaught_exception_handler`

### PR DESCRIPTION
**Pull request by ggreif**
we have OCaml 4.12 now, so `Printexc` provides it

### CODE REVIEW

**Comment by osa1** [comment]
Does this change the error output in any way?

**Comment by ggreif** [comment]
> Does this change the error output in any way?

No. But I so far haven't figured out how to get backtraces, so that's a point that remains to be clarified.

**Comment by osa1** [comment]
> so far haven't figured out how to get backtraces

I think you need `OCAMLRUNPARAM=b` before running.

LGTM but if this changes the output it would be good to show before and after in the commit message.

**Review by osa1 — APPROVED** [review]

**Comment by ggreif** [comment]
The function replacing ours is  https://github.com/ocaml/ocaml/pull/9263/files#diff-5fa438e4a308c8dfd6c75768649ae4fe17b72159d89f5ae3e7319c8eeaf2b790R273 and looks exactly the same.

**Pull request merged**
