### PR TITLE
LANG-28: flesh out a concept for reflected type parameters

### PR DESCRIPTION
**Pull request by ggreif**
Researching a type reflection mechanism. JIRA: https://dfinity.atlassian.net/browse/LANG-28.

I expect that deconstruction will be rather easy, but construction will be very tricky (needs CPS?).

### CODE REVIEW

**Comment by ggreif** [comment]
As of 14051b1a3b540314328819d723ebebb2d4cda206 the following abilities are present
- [ ] analysis side (deconstruct `A`)
  - [ ] primitive types
  - [ ] pairs (tuples?)
  - [ ] up-structuring (integrate `A` into something bigger)
  - [ ] variants
- [ ] synthesis side

**Comment by ggreif** [comment]
see also https://github.com/dfinity/motoko/issues/2348

**Comment by ggreif** [comment]
In today's _ICP.Lab_ Motoko office hours the following simplified context came up:
``` Motoko
func ws_send<to_candid A>(data : A)
```
would allow using `to_candid(data)` to obtain a `Blob`, where the caller would pass in a conversion (serialisation) function implicitly.
Similarly
``` Motoko
func ws_receive<from_candid A>(blob : Blob) : A { let ?(a : A) = from_candid(blob) else trap(); a }
```
would work for deserialising.
Stacking would make sense too `<switch from_candid to_candid A>` etc. (not pretty though...)

**Comment by luc-blaeser** [comment]
Just doing some repo cleanup for better focussing on active work:
Closing PR as it seems inactive for a longer time. Please re-open if it is still relevant and after it has been updated with latest master changes.

**Comment by ggreif** [comment]
Here are a few new ideas I had recently:
Declare parametric functions like this:
``` Motoko
type Const<T> = T; // just to make it more complicated
func foo<T>(arg : Const<T> with type) = switch arg with type {
  case 5 with type Nat: "It's a natural";
  case (?"Joker!") with type ?Text: "text-option"
};
```
Maybe have this shorthand (valid syntax already) expanding to `with type` in the above context:
```
  case (?"Joker!" : ?Text): "text-option"
```
For now I'd restrict type passing to `to_candid`-capable values, and would pass the Candid type representation behind the scenes suitably interpreting it in the `with type`-style `switch`.

**Comment by rvanasa** [comment]
This would be highly useful for the base library, since we could simplify type conversions, equality, comparison, etc. Maybe we could find a way to extend this for record / object types with unknown fields for use cases such as (de)serialization.

**Pull request closed without merging**
